service: sandwich
image: ghcr.io/sausage-sandwich/sandwich

servers:
  - 138.68.124.8

proxy:
  ssl: true
  host: 138.68.124.8

registry:
  server: ghcr.io
  username: sausage-sandwich
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_TO_STDOUT: "true"
    RAILS_SERVE_STATIC_FILES: "true"

ssh:
  user: sandwich

builder:
  arch: amd64
